//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephtan.DictService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DictService.DictFindRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestUserNo {
            get {
                return this.RequestUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserNoField, value) != true)) {
                    this.RequestUserNoField = value;
                    this.RaisePropertyChanged("RequestUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestUserId {
            get {
                return this.RequestUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserIdField, value) != true)) {
                    this.RequestUserIdField = value;
                    this.RaisePropertyChanged("RequestUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictFindRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DictFindRequest : Elephtan.DictService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictId1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DictId1 {
            get {
                return this.DictId1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DictId1Field, value) != true)) {
                    this.DictId1Field = value;
                    this.RaisePropertyChanged("DictId1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DictTypeId {
            get {
                return this.DictTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DictTypeIdField, value) != true)) {
                    this.DictTypeIdField = value;
                    this.RaisePropertyChanged("DictTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DictName {
            get {
                return this.DictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DictNameField, value) != true)) {
                    this.DictNameField = value;
                    this.RaisePropertyChanged("DictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DictTypeCode {
            get {
                return this.DictTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DictTypeCodeField, value) != true)) {
                    this.DictTypeCodeField = value;
                    this.RaisePropertyChanged("DictTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DictValue {
            get {
                return this.DictValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DictValueField, value) != true)) {
                    this.DictValueField = value;
                    this.RaisePropertyChanged("DictValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DictService.DictFindResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DictService.DictFindListResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictFindResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DictFindResponse : Elephtan.DictService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DictId {
            get {
                return this.DictIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DictIdField, value) != true)) {
                    this.DictIdField = value;
                    this.RaisePropertyChanged("DictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DictTypeId {
            get {
                return this.DictTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DictTypeIdField, value) != true)) {
                    this.DictTypeIdField = value;
                    this.RaisePropertyChanged("DictTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DictName {
            get {
                return this.DictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DictNameField, value) != true)) {
                    this.DictNameField = value;
                    this.RaisePropertyChanged("DictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DictTypeCode {
            get {
                return this.DictTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DictTypeCodeField, value) != true)) {
                    this.DictTypeCodeField = value;
                    this.RaisePropertyChanged("DictTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DictValue {
            get {
                return this.DictValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DictValueField, value) != true)) {
                    this.DictValueField = value;
                    this.RaisePropertyChanged("DictValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictFindListResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DictFindListResponse : Elephtan.DictService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.DictService.DictFindResponse[] ListResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Elephtan.DictService.DictFindResponse[] ListResponse {
            get {
                return this.ListResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ListResponseField, value) != true)) {
                    this.ListResponseField = value;
                    this.RaisePropertyChanged("ListResponse");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie", ConfigurationName="DictService.DictServiceSoap")]
    public interface DictServiceSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDictList", ReplyAction="*")]
        Elephtan.DictService.QueryDictListResponse QueryDictList(Elephtan.DictService.QueryDictListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDictList", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DictService.QueryDictListResponse> QueryDictListAsync(Elephtan.DictService.QueryDictListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDictListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDictList", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DictService.QueryDictListRequestBody Body;
        
        public QueryDictListRequest() {
        }
        
        public QueryDictListRequest(Elephtan.DictService.QueryDictListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDictListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DictService.DictFindRequest request;
        
        public QueryDictListRequestBody() {
        }
        
        public QueryDictListRequestBody(Elephtan.DictService.DictFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDictListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDictListResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DictService.QueryDictListResponseBody Body;
        
        public QueryDictListResponse() {
        }
        
        public QueryDictListResponse(Elephtan.DictService.QueryDictListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDictListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DictService.DictFindListResponse QueryDictListResult;
        
        public QueryDictListResponseBody() {
        }
        
        public QueryDictListResponseBody(Elephtan.DictService.DictFindListResponse QueryDictListResult) {
            this.QueryDictListResult = QueryDictListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictServiceSoapChannel : Elephtan.DictService.DictServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictServiceSoapClient : System.ServiceModel.ClientBase<Elephtan.DictService.DictServiceSoap>, Elephtan.DictService.DictServiceSoap {
        
        public DictServiceSoapClient() {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DictService.QueryDictListResponse Elephtan.DictService.DictServiceSoap.QueryDictList(Elephtan.DictService.QueryDictListRequest request) {
            return base.Channel.QueryDictList(request);
        }
        
        public Elephtan.DictService.DictFindListResponse QueryDictList(Elephtan.DictService.DictFindRequest request) {
            Elephtan.DictService.QueryDictListRequest inValue = new Elephtan.DictService.QueryDictListRequest();
            inValue.Body = new Elephtan.DictService.QueryDictListRequestBody();
            inValue.Body.request = request;
            Elephtan.DictService.QueryDictListResponse retVal = ((Elephtan.DictService.DictServiceSoap)(this)).QueryDictList(inValue);
            return retVal.Body.QueryDictListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DictService.QueryDictListResponse> Elephtan.DictService.DictServiceSoap.QueryDictListAsync(Elephtan.DictService.QueryDictListRequest request) {
            return base.Channel.QueryDictListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DictService.QueryDictListResponse> QueryDictListAsync(Elephtan.DictService.DictFindRequest request) {
            Elephtan.DictService.QueryDictListRequest inValue = new Elephtan.DictService.QueryDictListRequest();
            inValue.Body = new Elephtan.DictService.QueryDictListRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DictService.DictServiceSoap)(this)).QueryDictListAsync(inValue);
        }
    }
}
