//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephtan.CollectionPointService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.CollectionPointService.CollectionPointFindRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestUserNo {
            get {
                return this.RequestUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserNoField, value) != true)) {
                    this.RequestUserNoField = value;
                    this.RaisePropertyChanged("RequestUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestUserId {
            get {
                return this.RequestUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserIdField, value) != true)) {
                    this.RequestUserIdField = value;
                    this.RaisePropertyChanged("RequestUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointFindRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class CollectionPointFindRequest : Elephtan.CollectionPointService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreClerkIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CollectionPointId {
            get {
                return this.CollectionPointIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionPointIdField, value) != true)) {
                    this.CollectionPointIdField = value;
                    this.RaisePropertyChanged("CollectionPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionTime {
            get {
                return this.CollectionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionTimeField, value) != true)) {
                    this.CollectionTimeField = value;
                    this.RaisePropertyChanged("CollectionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StoreClerkId {
            get {
                return this.StoreClerkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreClerkIdField, value) != true)) {
                    this.StoreClerkIdField = value;
                    this.RaisePropertyChanged("StoreClerkId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.CollectionPointService.CollectionPointFindListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.CollectionPointService.CollectionPointFindResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointFindListResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class CollectionPointFindListResponse : Elephtan.CollectionPointService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.CollectionPointService.CollectionPointFindResponse[] ListResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Elephtan.CollectionPointService.CollectionPointFindResponse[] ListResponse {
            get {
                return this.ListResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ListResponseField, value) != true)) {
                    this.ListResponseField = value;
                    this.RaisePropertyChanged("ListResponse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionPointFindResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class CollectionPointFindResponse : Elephtan.CollectionPointService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreClerkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClertNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CollectionPointId {
            get {
                return this.CollectionPointIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionPointIdField, value) != true)) {
                    this.CollectionPointIdField = value;
                    this.RaisePropertyChanged("CollectionPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionTime {
            get {
                return this.CollectionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionTimeField, value) != true)) {
                    this.CollectionTimeField = value;
                    this.RaisePropertyChanged("CollectionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StoreClerkId {
            get {
                return this.StoreClerkIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreClerkIdField, value) != true)) {
                    this.StoreClerkIdField = value;
                    this.RaisePropertyChanged("StoreClerkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClertName {
            get {
                return this.ClertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClertNameField, value) != true)) {
                    this.ClertNameField = value;
                    this.RaisePropertyChanged("ClertName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie", ConfigurationName="CollectionPointService.CollectionPointServiceSoap")]
    public interface CollectionPointServiceSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryCollectionById", ReplyAction="*")]
        Elephtan.CollectionPointService.QueryCollectionByIdResponse QueryCollectionById(Elephtan.CollectionPointService.QueryCollectionByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryCollectionById", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionByIdResponse> QueryCollectionByIdAsync(Elephtan.CollectionPointService.QueryCollectionByIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryCollectionList", ReplyAction="*")]
        Elephtan.CollectionPointService.QueryCollectionListResponse QueryCollectionList(Elephtan.CollectionPointService.QueryCollectionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryCollectionList", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionListResponse> QueryCollectionListAsync(Elephtan.CollectionPointService.QueryCollectionListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryCollectionByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryCollectionById", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.CollectionPointService.QueryCollectionByIdRequestBody Body;
        
        public QueryCollectionByIdRequest() {
        }
        
        public QueryCollectionByIdRequest(Elephtan.CollectionPointService.QueryCollectionByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryCollectionByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.CollectionPointService.CollectionPointFindRequest request;
        
        public QueryCollectionByIdRequestBody() {
        }
        
        public QueryCollectionByIdRequestBody(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryCollectionByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryCollectionByIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.CollectionPointService.QueryCollectionByIdResponseBody Body;
        
        public QueryCollectionByIdResponse() {
        }
        
        public QueryCollectionByIdResponse(Elephtan.CollectionPointService.QueryCollectionByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryCollectionByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.CollectionPointService.CollectionPointFindResponse QueryCollectionByIdResult;
        
        public QueryCollectionByIdResponseBody() {
        }
        
        public QueryCollectionByIdResponseBody(Elephtan.CollectionPointService.CollectionPointFindResponse QueryCollectionByIdResult) {
            this.QueryCollectionByIdResult = QueryCollectionByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryCollectionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryCollectionList", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.CollectionPointService.QueryCollectionListRequestBody Body;
        
        public QueryCollectionListRequest() {
        }
        
        public QueryCollectionListRequest(Elephtan.CollectionPointService.QueryCollectionListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryCollectionListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.CollectionPointService.CollectionPointFindRequest request;
        
        public QueryCollectionListRequestBody() {
        }
        
        public QueryCollectionListRequestBody(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryCollectionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryCollectionListResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.CollectionPointService.QueryCollectionListResponseBody Body;
        
        public QueryCollectionListResponse() {
        }
        
        public QueryCollectionListResponse(Elephtan.CollectionPointService.QueryCollectionListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryCollectionListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.CollectionPointService.CollectionPointFindListResponse QueryCollectionListResult;
        
        public QueryCollectionListResponseBody() {
        }
        
        public QueryCollectionListResponseBody(Elephtan.CollectionPointService.CollectionPointFindListResponse QueryCollectionListResult) {
            this.QueryCollectionListResult = QueryCollectionListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CollectionPointServiceSoapChannel : Elephtan.CollectionPointService.CollectionPointServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollectionPointServiceSoapClient : System.ServiceModel.ClientBase<Elephtan.CollectionPointService.CollectionPointServiceSoap>, Elephtan.CollectionPointService.CollectionPointServiceSoap {
        
        public CollectionPointServiceSoapClient() {
        }
        
        public CollectionPointServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollectionPointServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionPointServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionPointServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.CollectionPointService.QueryCollectionByIdResponse Elephtan.CollectionPointService.CollectionPointServiceSoap.QueryCollectionById(Elephtan.CollectionPointService.QueryCollectionByIdRequest request) {
            return base.Channel.QueryCollectionById(request);
        }
        
        public Elephtan.CollectionPointService.CollectionPointFindResponse QueryCollectionById(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            Elephtan.CollectionPointService.QueryCollectionByIdRequest inValue = new Elephtan.CollectionPointService.QueryCollectionByIdRequest();
            inValue.Body = new Elephtan.CollectionPointService.QueryCollectionByIdRequestBody();
            inValue.Body.request = request;
            Elephtan.CollectionPointService.QueryCollectionByIdResponse retVal = ((Elephtan.CollectionPointService.CollectionPointServiceSoap)(this)).QueryCollectionById(inValue);
            return retVal.Body.QueryCollectionByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionByIdResponse> Elephtan.CollectionPointService.CollectionPointServiceSoap.QueryCollectionByIdAsync(Elephtan.CollectionPointService.QueryCollectionByIdRequest request) {
            return base.Channel.QueryCollectionByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionByIdResponse> QueryCollectionByIdAsync(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            Elephtan.CollectionPointService.QueryCollectionByIdRequest inValue = new Elephtan.CollectionPointService.QueryCollectionByIdRequest();
            inValue.Body = new Elephtan.CollectionPointService.QueryCollectionByIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.CollectionPointService.CollectionPointServiceSoap)(this)).QueryCollectionByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.CollectionPointService.QueryCollectionListResponse Elephtan.CollectionPointService.CollectionPointServiceSoap.QueryCollectionList(Elephtan.CollectionPointService.QueryCollectionListRequest request) {
            return base.Channel.QueryCollectionList(request);
        }
        
        public Elephtan.CollectionPointService.CollectionPointFindListResponse QueryCollectionList(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            Elephtan.CollectionPointService.QueryCollectionListRequest inValue = new Elephtan.CollectionPointService.QueryCollectionListRequest();
            inValue.Body = new Elephtan.CollectionPointService.QueryCollectionListRequestBody();
            inValue.Body.request = request;
            Elephtan.CollectionPointService.QueryCollectionListResponse retVal = ((Elephtan.CollectionPointService.CollectionPointServiceSoap)(this)).QueryCollectionList(inValue);
            return retVal.Body.QueryCollectionListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionListResponse> Elephtan.CollectionPointService.CollectionPointServiceSoap.QueryCollectionListAsync(Elephtan.CollectionPointService.QueryCollectionListRequest request) {
            return base.Channel.QueryCollectionListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.CollectionPointService.QueryCollectionListResponse> QueryCollectionListAsync(Elephtan.CollectionPointService.CollectionPointFindRequest request) {
            Elephtan.CollectionPointService.QueryCollectionListRequest inValue = new Elephtan.CollectionPointService.QueryCollectionListRequest();
            inValue.Body = new Elephtan.CollectionPointService.QueryCollectionListRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.CollectionPointService.CollectionPointServiceSoap)(this)).QueryCollectionListAsync(inValue);
        }
    }
}
