//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephtan.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.UserService.UserFindListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.UserService.UserFindRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestUserNo {
            get {
                return this.RequestUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserNoField, value) != true)) {
                    this.RequestUserNoField = value;
                    this.RaisePropertyChanged("RequestUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestUserId {
            get {
                return this.RequestUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserIdField, value) != true)) {
                    this.RequestUserIdField = value;
                    this.RaisePropertyChanged("RequestUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFindListRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class UserFindListRequest : Elephtan.UserService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFindRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class UserFindRequest : Elephtan.UserService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GcmRegistrationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserNo {
            get {
                return this.UserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNoField, value) != true)) {
                    this.UserNoField = value;
                    this.RaisePropertyChanged("UserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GcmRegistration {
            get {
                return this.GcmRegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.GcmRegistrationField, value) != true)) {
                    this.GcmRegistrationField = value;
                    this.RaisePropertyChanged("GcmRegistration");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.UserService.UserFindListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.UserService.UserFindResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFindListResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class UserFindListResponse : Elephtan.UserService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.UserService.UserFindResponse[] UserFindResponseListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Elephtan.UserService.UserFindResponse[] UserFindResponseList {
            get {
                return this.UserFindResponseListField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFindResponseListField, value) != true)) {
                    this.UserFindResponseListField = value;
                    this.RaisePropertyChanged("UserFindResponseList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFindResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class UserFindResponse : Elephtan.UserService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GcmRegritrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.UserService.RoleEntry[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelegationFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GcmRegritration {
            get {
                return this.GcmRegritrationField;
            }
            set {
                if ((object.ReferenceEquals(this.GcmRegritrationField, value) != true)) {
                    this.GcmRegritrationField = value;
                    this.RaisePropertyChanged("GcmRegritration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserNo {
            get {
                return this.UserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNoField, value) != true)) {
                    this.UserNoField = value;
                    this.RaisePropertyChanged("UserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UserStatus {
            get {
                return this.UserStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.UserStatusField, value) != true)) {
                    this.UserStatusField = value;
                    this.RaisePropertyChanged("UserStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TelephoneNo {
            get {
                return this.TelephoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNoField, value) != true)) {
                    this.TelephoneNoField = value;
                    this.RaisePropertyChanged("TelephoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Elephtan.UserService.RoleEntry[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DepartmentCode {
            get {
                return this.DepartmentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCodeField, value) != true)) {
                    this.DepartmentCodeField = value;
                    this.RaisePropertyChanged("DepartmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DelegationFlag {
            get {
                return this.DelegationFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.DelegationFlagField, value) != true)) {
                    this.DelegationFlagField = value;
                    this.RaisePropertyChanged("DelegationFlag");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleEntry", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class RoleEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.UserService.MenuEntry[] MenusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleCode {
            get {
                return this.RoleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleCodeField, value) != true)) {
                    this.RoleCodeField = value;
                    this.RaisePropertyChanged("RoleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Elephtan.UserService.MenuEntry[] Menus {
            get {
                return this.MenusField;
            }
            set {
                if ((object.ReferenceEquals(this.MenusField, value) != true)) {
                    this.MenusField = value;
                    this.RaisePropertyChanged("Menus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuEntry", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class MenuEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MenuName {
            get {
                return this.MenuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuNameField, value) != true)) {
                    this.MenuNameField = value;
                    this.RaisePropertyChanged("MenuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie", ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUserByNum", ReplyAction="*")]
        Elephtan.UserService.QueryUserByNumResponse QueryUserByNum(Elephtan.UserService.QueryUserByNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUserByNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByNumResponse> QueryUserByNumAsync(Elephtan.UserService.QueryUserByNumRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUserById", ReplyAction="*")]
        Elephtan.UserService.QueryUserByIdResponse QueryUserById(Elephtan.UserService.QueryUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByIdResponse> QueryUserByIdAsync(Elephtan.UserService.QueryUserByIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUsersByDepartmentId", ReplyAction="*")]
        Elephtan.UserService.QueryUsersByDepartmentIdResponse QueryUsersByDepartmentId(Elephtan.UserService.QueryUsersByDepartmentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryUsersByDepartmentId", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUsersByDepartmentIdResponse> QueryUsersByDepartmentIdAsync(Elephtan.UserService.QueryUsersByDepartmentIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/updategcmregistration", ReplyAction="*")]
        Elephtan.UserService.updategcmregistrationResponse updategcmregistration(Elephtan.UserService.updategcmregistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/updategcmregistration", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.UserService.updategcmregistrationResponse> updategcmregistrationAsync(Elephtan.UserService.updategcmregistrationRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/FindGcmRegistrationByUserId", ReplyAction="*")]
        Elephtan.UserService.FindGcmRegistrationByUserIdResponse FindGcmRegistrationByUserId(Elephtan.UserService.FindGcmRegistrationByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/FindGcmRegistrationByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.UserService.FindGcmRegistrationByUserIdResponse> FindGcmRegistrationByUserIdAsync(Elephtan.UserService.FindGcmRegistrationByUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserByNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserByNum", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUserByNumRequestBody Body;
        
        public QueryUserByNumRequest() {
        }
        
        public QueryUserByNumRequest(Elephtan.UserService.QueryUserByNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUserByNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindRequest request;
        
        public QueryUserByNumRequestBody() {
        }
        
        public QueryUserByNumRequestBody(Elephtan.UserService.UserFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserByNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserByNumResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUserByNumResponseBody Body;
        
        public QueryUserByNumResponse() {
        }
        
        public QueryUserByNumResponse(Elephtan.UserService.QueryUserByNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUserByNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindResponse QueryUserByNumResult;
        
        public QueryUserByNumResponseBody() {
        }
        
        public QueryUserByNumResponseBody(Elephtan.UserService.UserFindResponse QueryUserByNumResult) {
            this.QueryUserByNumResult = QueryUserByNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserById", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUserByIdRequestBody Body;
        
        public QueryUserByIdRequest() {
        }
        
        public QueryUserByIdRequest(Elephtan.UserService.QueryUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindRequest request;
        
        public QueryUserByIdRequestBody() {
        }
        
        public QueryUserByIdRequestBody(Elephtan.UserService.UserFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUserByIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUserByIdResponseBody Body;
        
        public QueryUserByIdResponse() {
        }
        
        public QueryUserByIdResponse(Elephtan.UserService.QueryUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindResponse QueryUserByIdResult;
        
        public QueryUserByIdResponseBody() {
        }
        
        public QueryUserByIdResponseBody(Elephtan.UserService.UserFindResponse QueryUserByIdResult) {
            this.QueryUserByIdResult = QueryUserByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUsersByDepartmentIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUsersByDepartmentId", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUsersByDepartmentIdRequestBody Body;
        
        public QueryUsersByDepartmentIdRequest() {
        }
        
        public QueryUsersByDepartmentIdRequest(Elephtan.UserService.QueryUsersByDepartmentIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUsersByDepartmentIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindListRequest request;
        
        public QueryUsersByDepartmentIdRequestBody() {
        }
        
        public QueryUsersByDepartmentIdRequestBody(Elephtan.UserService.UserFindListRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUsersByDepartmentIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUsersByDepartmentIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.QueryUsersByDepartmentIdResponseBody Body;
        
        public QueryUsersByDepartmentIdResponse() {
        }
        
        public QueryUsersByDepartmentIdResponse(Elephtan.UserService.QueryUsersByDepartmentIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryUsersByDepartmentIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindListResponse QueryUsersByDepartmentIdResult;
        
        public QueryUsersByDepartmentIdResponseBody() {
        }
        
        public QueryUsersByDepartmentIdResponseBody(Elephtan.UserService.UserFindListResponse QueryUsersByDepartmentIdResult) {
            this.QueryUsersByDepartmentIdResult = QueryUsersByDepartmentIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updategcmregistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updategcmregistration", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.updategcmregistrationRequestBody Body;
        
        public updategcmregistrationRequest() {
        }
        
        public updategcmregistrationRequest(Elephtan.UserService.updategcmregistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class updategcmregistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindRequest request;
        
        public updategcmregistrationRequestBody() {
        }
        
        public updategcmregistrationRequestBody(Elephtan.UserService.UserFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updategcmregistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updategcmregistrationResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.updategcmregistrationResponseBody Body;
        
        public updategcmregistrationResponse() {
        }
        
        public updategcmregistrationResponse(Elephtan.UserService.updategcmregistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class updategcmregistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindResponse updategcmregistrationResult;
        
        public updategcmregistrationResponseBody() {
        }
        
        public updategcmregistrationResponseBody(Elephtan.UserService.UserFindResponse updategcmregistrationResult) {
            this.updategcmregistrationResult = updategcmregistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindGcmRegistrationByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindGcmRegistrationByUserId", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.FindGcmRegistrationByUserIdRequestBody Body;
        
        public FindGcmRegistrationByUserIdRequest() {
        }
        
        public FindGcmRegistrationByUserIdRequest(Elephtan.UserService.FindGcmRegistrationByUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class FindGcmRegistrationByUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindRequest request;
        
        public FindGcmRegistrationByUserIdRequestBody() {
        }
        
        public FindGcmRegistrationByUserIdRequestBody(Elephtan.UserService.UserFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindGcmRegistrationByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindGcmRegistrationByUserIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.UserService.FindGcmRegistrationByUserIdResponseBody Body;
        
        public FindGcmRegistrationByUserIdResponse() {
        }
        
        public FindGcmRegistrationByUserIdResponse(Elephtan.UserService.FindGcmRegistrationByUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class FindGcmRegistrationByUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.UserService.UserFindResponse FindGcmRegistrationByUserIdResult;
        
        public FindGcmRegistrationByUserIdResponseBody() {
        }
        
        public FindGcmRegistrationByUserIdResponseBody(Elephtan.UserService.UserFindResponse FindGcmRegistrationByUserIdResult) {
            this.FindGcmRegistrationByUserIdResult = FindGcmRegistrationByUserIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : Elephtan.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<Elephtan.UserService.UserServiceSoap>, Elephtan.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.UserService.QueryUserByNumResponse Elephtan.UserService.UserServiceSoap.QueryUserByNum(Elephtan.UserService.QueryUserByNumRequest request) {
            return base.Channel.QueryUserByNum(request);
        }
        
        public Elephtan.UserService.UserFindResponse QueryUserByNum(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.QueryUserByNumRequest inValue = new Elephtan.UserService.QueryUserByNumRequest();
            inValue.Body = new Elephtan.UserService.QueryUserByNumRequestBody();
            inValue.Body.request = request;
            Elephtan.UserService.QueryUserByNumResponse retVal = ((Elephtan.UserService.UserServiceSoap)(this)).QueryUserByNum(inValue);
            return retVal.Body.QueryUserByNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByNumResponse> Elephtan.UserService.UserServiceSoap.QueryUserByNumAsync(Elephtan.UserService.QueryUserByNumRequest request) {
            return base.Channel.QueryUserByNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByNumResponse> QueryUserByNumAsync(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.QueryUserByNumRequest inValue = new Elephtan.UserService.QueryUserByNumRequest();
            inValue.Body = new Elephtan.UserService.QueryUserByNumRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.UserService.UserServiceSoap)(this)).QueryUserByNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.UserService.QueryUserByIdResponse Elephtan.UserService.UserServiceSoap.QueryUserById(Elephtan.UserService.QueryUserByIdRequest request) {
            return base.Channel.QueryUserById(request);
        }
        
        public Elephtan.UserService.UserFindResponse QueryUserById(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.QueryUserByIdRequest inValue = new Elephtan.UserService.QueryUserByIdRequest();
            inValue.Body = new Elephtan.UserService.QueryUserByIdRequestBody();
            inValue.Body.request = request;
            Elephtan.UserService.QueryUserByIdResponse retVal = ((Elephtan.UserService.UserServiceSoap)(this)).QueryUserById(inValue);
            return retVal.Body.QueryUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByIdResponse> Elephtan.UserService.UserServiceSoap.QueryUserByIdAsync(Elephtan.UserService.QueryUserByIdRequest request) {
            return base.Channel.QueryUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.UserService.QueryUserByIdResponse> QueryUserByIdAsync(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.QueryUserByIdRequest inValue = new Elephtan.UserService.QueryUserByIdRequest();
            inValue.Body = new Elephtan.UserService.QueryUserByIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.UserService.UserServiceSoap)(this)).QueryUserByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.UserService.QueryUsersByDepartmentIdResponse Elephtan.UserService.UserServiceSoap.QueryUsersByDepartmentId(Elephtan.UserService.QueryUsersByDepartmentIdRequest request) {
            return base.Channel.QueryUsersByDepartmentId(request);
        }
        
        public Elephtan.UserService.UserFindListResponse QueryUsersByDepartmentId(Elephtan.UserService.UserFindListRequest request) {
            Elephtan.UserService.QueryUsersByDepartmentIdRequest inValue = new Elephtan.UserService.QueryUsersByDepartmentIdRequest();
            inValue.Body = new Elephtan.UserService.QueryUsersByDepartmentIdRequestBody();
            inValue.Body.request = request;
            Elephtan.UserService.QueryUsersByDepartmentIdResponse retVal = ((Elephtan.UserService.UserServiceSoap)(this)).QueryUsersByDepartmentId(inValue);
            return retVal.Body.QueryUsersByDepartmentIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.UserService.QueryUsersByDepartmentIdResponse> Elephtan.UserService.UserServiceSoap.QueryUsersByDepartmentIdAsync(Elephtan.UserService.QueryUsersByDepartmentIdRequest request) {
            return base.Channel.QueryUsersByDepartmentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.UserService.QueryUsersByDepartmentIdResponse> QueryUsersByDepartmentIdAsync(Elephtan.UserService.UserFindListRequest request) {
            Elephtan.UserService.QueryUsersByDepartmentIdRequest inValue = new Elephtan.UserService.QueryUsersByDepartmentIdRequest();
            inValue.Body = new Elephtan.UserService.QueryUsersByDepartmentIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.UserService.UserServiceSoap)(this)).QueryUsersByDepartmentIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.UserService.updategcmregistrationResponse Elephtan.UserService.UserServiceSoap.updategcmregistration(Elephtan.UserService.updategcmregistrationRequest request) {
            return base.Channel.updategcmregistration(request);
        }
        
        public Elephtan.UserService.UserFindResponse updategcmregistration(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.updategcmregistrationRequest inValue = new Elephtan.UserService.updategcmregistrationRequest();
            inValue.Body = new Elephtan.UserService.updategcmregistrationRequestBody();
            inValue.Body.request = request;
            Elephtan.UserService.updategcmregistrationResponse retVal = ((Elephtan.UserService.UserServiceSoap)(this)).updategcmregistration(inValue);
            return retVal.Body.updategcmregistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.UserService.updategcmregistrationResponse> Elephtan.UserService.UserServiceSoap.updategcmregistrationAsync(Elephtan.UserService.updategcmregistrationRequest request) {
            return base.Channel.updategcmregistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.UserService.updategcmregistrationResponse> updategcmregistrationAsync(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.updategcmregistrationRequest inValue = new Elephtan.UserService.updategcmregistrationRequest();
            inValue.Body = new Elephtan.UserService.updategcmregistrationRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.UserService.UserServiceSoap)(this)).updategcmregistrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.UserService.FindGcmRegistrationByUserIdResponse Elephtan.UserService.UserServiceSoap.FindGcmRegistrationByUserId(Elephtan.UserService.FindGcmRegistrationByUserIdRequest request) {
            return base.Channel.FindGcmRegistrationByUserId(request);
        }
        
        public Elephtan.UserService.UserFindResponse FindGcmRegistrationByUserId(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.FindGcmRegistrationByUserIdRequest inValue = new Elephtan.UserService.FindGcmRegistrationByUserIdRequest();
            inValue.Body = new Elephtan.UserService.FindGcmRegistrationByUserIdRequestBody();
            inValue.Body.request = request;
            Elephtan.UserService.FindGcmRegistrationByUserIdResponse retVal = ((Elephtan.UserService.UserServiceSoap)(this)).FindGcmRegistrationByUserId(inValue);
            return retVal.Body.FindGcmRegistrationByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.UserService.FindGcmRegistrationByUserIdResponse> Elephtan.UserService.UserServiceSoap.FindGcmRegistrationByUserIdAsync(Elephtan.UserService.FindGcmRegistrationByUserIdRequest request) {
            return base.Channel.FindGcmRegistrationByUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.UserService.FindGcmRegistrationByUserIdResponse> FindGcmRegistrationByUserIdAsync(Elephtan.UserService.UserFindRequest request) {
            Elephtan.UserService.FindGcmRegistrationByUserIdRequest inValue = new Elephtan.UserService.FindGcmRegistrationByUserIdRequest();
            inValue.Body = new Elephtan.UserService.FindGcmRegistrationByUserIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.UserService.UserServiceSoap)(this)).FindGcmRegistrationByUserIdAsync(inValue);
        }
    }
}
