//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephtan.DisbursementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementFindListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementFindRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementDetailManageRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementManageRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestUserNo {
            get {
                return this.RequestUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserNoField, value) != true)) {
                    this.RequestUserNoField = value;
                    this.RaisePropertyChanged("RequestUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestUserId {
            get {
                return this.RequestUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserIdField, value) != true)) {
                    this.RequestUserIdField = value;
                    this.RaisePropertyChanged("RequestUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementFindListRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementFindListRequest : Elephtan.DisbursementService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementStatus {
            get {
                return this.DisbursementStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementStatusField, value) != true)) {
                    this.DisbursementStatusField = value;
                    this.RaisePropertyChanged("DisbursementStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementFindRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementFindRequest : Elephtan.DisbursementService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementDetailManageRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementDetailManageRequest : Elephtan.DisbursementService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementDetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppliedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedQuanntityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementDetailId {
            get {
                return this.DisbursementDetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementDetailIdField, value) != true)) {
                    this.DisbursementDetailIdField = value;
                    this.RaisePropertyChanged("DisbursementDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AppliedQuantity {
            get {
                return this.AppliedQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.AppliedQuantityField, value) != true)) {
                    this.AppliedQuantityField = value;
                    this.RaisePropertyChanged("AppliedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AssignedQuanntity {
            get {
                return this.AssignedQuanntityField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedQuanntityField, value) != true)) {
                    this.AssignedQuanntityField = value;
                    this.RaisePropertyChanged("AssignedQuanntity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementManageRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementManageRequest : Elephtan.DisbursementService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetrievingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.DisbursementService.DisbursementDetail[] DetailListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetrievingId {
            get {
                return this.RetrievingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RetrievingIdField, value) != true)) {
                    this.RetrievingIdField = value;
                    this.RaisePropertyChanged("RetrievingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Elephtan.DisbursementService.DisbursementDetail[] DetailList {
            get {
                return this.DetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailListField, value) != true)) {
                    this.DetailListField = value;
                    this.RaisePropertyChanged("DetailList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementDetail", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementDetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppliedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DisbursementDetailId {
            get {
                return this.DisbursementDetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementDetailIdField, value) != true)) {
                    this.DisbursementDetailIdField = value;
                    this.RaisePropertyChanged("DisbursementDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AppliedQuantity {
            get {
                return this.AppliedQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.AppliedQuantityField, value) != true)) {
                    this.AppliedQuantityField = value;
                    this.RaisePropertyChanged("AppliedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AssignedQuantity {
            get {
                return this.AssignedQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedQuantityField, value) != true)) {
                    this.AssignedQuantityField = value;
                    this.RaisePropertyChanged("AssignedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ItemNum {
            get {
                return this.ItemNumField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumField, value) != true)) {
                    this.ItemNumField = value;
                    this.RaisePropertyChanged("ItemNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementFindListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementFindResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementDetailManageResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.DisbursementService.DisbursementManageResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementFindListResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementFindListResponse : Elephtan.DisbursementService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.DisbursementService.DisbursementFindResponse[] DisbursementFindResponseListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Elephtan.DisbursementService.DisbursementFindResponse[] DisbursementFindResponseList {
            get {
                return this.DisbursementFindResponseListField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementFindResponseListField, value) != true)) {
                    this.DisbursementFindResponseListField = value;
                    this.RaisePropertyChanged("DisbursementFindResponseList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementFindResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementFindResponse : Elephtan.DisbursementService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepresentativeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionPointAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepresentativeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.DisbursementService.DisbursementDetail[] DisbursementDetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RepresentativeNo {
            get {
                return this.RepresentativeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentativeNoField, value) != true)) {
                    this.RepresentativeNoField = value;
                    this.RaisePropertyChanged("RepresentativeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CollectionPointAddress {
            get {
                return this.CollectionPointAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionPointAddressField, value) != true)) {
                    this.CollectionPointAddressField = value;
                    this.RaisePropertyChanged("CollectionPointAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionTime {
            get {
                return this.CollectionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionTimeField, value) != true)) {
                    this.CollectionTimeField = value;
                    this.RaisePropertyChanged("CollectionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RepresentativeName {
            get {
                return this.RepresentativeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentativeNameField, value) != true)) {
                    this.RepresentativeNameField = value;
                    this.RaisePropertyChanged("RepresentativeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DisbursementNo {
            get {
                return this.DisbursementNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementNoField, value) != true)) {
                    this.DisbursementNoField = value;
                    this.RaisePropertyChanged("DisbursementNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdField, value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateTimeField, value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DisbursementStatus {
            get {
                return this.DisbursementStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementStatusField, value) != true)) {
                    this.DisbursementStatusField = value;
                    this.RaisePropertyChanged("DisbursementStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public Elephtan.DisbursementService.DisbursementDetail[] DisbursementDetailList {
            get {
                return this.DisbursementDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementDetailListField, value) != true)) {
                    this.DisbursementDetailListField = value;
                    this.RaisePropertyChanged("DisbursementDetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementDetailManageResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementDetailManageResponse : Elephtan.DisbursementService.ResponseMessage {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisbursementManageResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class DisbursementManageResponse : Elephtan.DisbursementService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisbursementIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisbursementId {
            get {
                return this.DisbursementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementIdField, value) != true)) {
                    this.DisbursementIdField = value;
                    this.RaisePropertyChanged("DisbursementId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie", ConfigurationName="DisbursementService.DisbursementServiceSoap")]
    public interface DisbursementServiceSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/GenerateDisbursementForm", ReplyAction="*")]
        Elephtan.DisbursementService.GenerateDisbursementFormResponse GenerateDisbursementForm(Elephtan.DisbursementService.GenerateDisbursementFormRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/GenerateDisbursementForm", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.GenerateDisbursementFormResponse> GenerateDisbursementFormAsync(Elephtan.DisbursementService.GenerateDisbursementFormRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDisbursementList", ReplyAction="*")]
        Elephtan.DisbursementService.QueryDisbursementListResponse QueryDisbursementList(Elephtan.DisbursementService.QueryDisbursementListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDisbursementList", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementListResponse> QueryDisbursementListAsync(Elephtan.DisbursementService.QueryDisbursementListRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDisbursementById", ReplyAction="*")]
        Elephtan.DisbursementService.QueryDisbursementByIdResponse QueryDisbursementById(Elephtan.DisbursementService.QueryDisbursementByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryDisbursementById", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementByIdResponse> QueryDisbursementByIdAsync(Elephtan.DisbursementService.QueryDisbursementByIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/ConfirmDepartmentDisbursement", ReplyAction="*")]
        Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse ConfirmDepartmentDisbursement(Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/ConfirmDepartmentDisbursement", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse> ConfirmDepartmentDisbursementAsync(Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/ConfirmStoreDisbursement", ReplyAction="*")]
        Elephtan.DisbursementService.ConfirmStoreDisbursementResponse ConfirmStoreDisbursement(Elephtan.DisbursementService.ConfirmStoreDisbursementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/ConfirmStoreDisbursement", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmStoreDisbursementResponse> ConfirmStoreDisbursementAsync(Elephtan.DisbursementService.ConfirmStoreDisbursementRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/UpdateDisbursementDetail", ReplyAction="*")]
        Elephtan.DisbursementService.UpdateDisbursementDetailResponse UpdateDisbursementDetail(Elephtan.DisbursementService.UpdateDisbursementDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/UpdateDisbursementDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.UpdateDisbursementDetailResponse> UpdateDisbursementDetailAsync(Elephtan.DisbursementService.UpdateDisbursementDetailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateDisbursementFormRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateDisbursementForm", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.GenerateDisbursementFormRequestBody Body;
        
        public GenerateDisbursementFormRequest() {
        }
        
        public GenerateDisbursementFormRequest(Elephtan.DisbursementService.GenerateDisbursementFormRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class GenerateDisbursementFormRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageRequest request;
        
        public GenerateDisbursementFormRequestBody() {
        }
        
        public GenerateDisbursementFormRequestBody(Elephtan.DisbursementService.DisbursementManageRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateDisbursementFormResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateDisbursementFormResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.GenerateDisbursementFormResponseBody Body;
        
        public GenerateDisbursementFormResponse() {
        }
        
        public GenerateDisbursementFormResponse(Elephtan.DisbursementService.GenerateDisbursementFormResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class GenerateDisbursementFormResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageResponse GenerateDisbursementFormResult;
        
        public GenerateDisbursementFormResponseBody() {
        }
        
        public GenerateDisbursementFormResponseBody(Elephtan.DisbursementService.DisbursementManageResponse GenerateDisbursementFormResult) {
            this.GenerateDisbursementFormResult = GenerateDisbursementFormResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDisbursementListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDisbursementList", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.QueryDisbursementListRequestBody Body;
        
        public QueryDisbursementListRequest() {
        }
        
        public QueryDisbursementListRequest(Elephtan.DisbursementService.QueryDisbursementListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDisbursementListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementFindListRequest request;
        
        public QueryDisbursementListRequestBody() {
        }
        
        public QueryDisbursementListRequestBody(Elephtan.DisbursementService.DisbursementFindListRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDisbursementListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDisbursementListResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.QueryDisbursementListResponseBody Body;
        
        public QueryDisbursementListResponse() {
        }
        
        public QueryDisbursementListResponse(Elephtan.DisbursementService.QueryDisbursementListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDisbursementListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementFindListResponse QueryDisbursementListResult;
        
        public QueryDisbursementListResponseBody() {
        }
        
        public QueryDisbursementListResponseBody(Elephtan.DisbursementService.DisbursementFindListResponse QueryDisbursementListResult) {
            this.QueryDisbursementListResult = QueryDisbursementListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDisbursementByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDisbursementById", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.QueryDisbursementByIdRequestBody Body;
        
        public QueryDisbursementByIdRequest() {
        }
        
        public QueryDisbursementByIdRequest(Elephtan.DisbursementService.QueryDisbursementByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDisbursementByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementFindRequest request;
        
        public QueryDisbursementByIdRequestBody() {
        }
        
        public QueryDisbursementByIdRequestBody(Elephtan.DisbursementService.DisbursementFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryDisbursementByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryDisbursementByIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.QueryDisbursementByIdResponseBody Body;
        
        public QueryDisbursementByIdResponse() {
        }
        
        public QueryDisbursementByIdResponse(Elephtan.DisbursementService.QueryDisbursementByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryDisbursementByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementFindResponse QueryDisbursementByIdResult;
        
        public QueryDisbursementByIdResponseBody() {
        }
        
        public QueryDisbursementByIdResponseBody(Elephtan.DisbursementService.DisbursementFindResponse QueryDisbursementByIdResult) {
            this.QueryDisbursementByIdResult = QueryDisbursementByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmDepartmentDisbursementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmDepartmentDisbursement", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequestBody Body;
        
        public ConfirmDepartmentDisbursementRequest() {
        }
        
        public ConfirmDepartmentDisbursementRequest(Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class ConfirmDepartmentDisbursementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageRequest request;
        
        public ConfirmDepartmentDisbursementRequestBody() {
        }
        
        public ConfirmDepartmentDisbursementRequestBody(Elephtan.DisbursementService.DisbursementManageRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmDepartmentDisbursementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmDepartmentDisbursementResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponseBody Body;
        
        public ConfirmDepartmentDisbursementResponse() {
        }
        
        public ConfirmDepartmentDisbursementResponse(Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class ConfirmDepartmentDisbursementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageResponse ConfirmDepartmentDisbursementResult;
        
        public ConfirmDepartmentDisbursementResponseBody() {
        }
        
        public ConfirmDepartmentDisbursementResponseBody(Elephtan.DisbursementService.DisbursementManageResponse ConfirmDepartmentDisbursementResult) {
            this.ConfirmDepartmentDisbursementResult = ConfirmDepartmentDisbursementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmStoreDisbursementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmStoreDisbursement", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.ConfirmStoreDisbursementRequestBody Body;
        
        public ConfirmStoreDisbursementRequest() {
        }
        
        public ConfirmStoreDisbursementRequest(Elephtan.DisbursementService.ConfirmStoreDisbursementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class ConfirmStoreDisbursementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageRequest request;
        
        public ConfirmStoreDisbursementRequestBody() {
        }
        
        public ConfirmStoreDisbursementRequestBody(Elephtan.DisbursementService.DisbursementManageRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmStoreDisbursementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmStoreDisbursementResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.ConfirmStoreDisbursementResponseBody Body;
        
        public ConfirmStoreDisbursementResponse() {
        }
        
        public ConfirmStoreDisbursementResponse(Elephtan.DisbursementService.ConfirmStoreDisbursementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class ConfirmStoreDisbursementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementManageResponse ConfirmStoreDisbursementResult;
        
        public ConfirmStoreDisbursementResponseBody() {
        }
        
        public ConfirmStoreDisbursementResponseBody(Elephtan.DisbursementService.DisbursementManageResponse ConfirmStoreDisbursementResult) {
            this.ConfirmStoreDisbursementResult = ConfirmStoreDisbursementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDisbursementDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDisbursementDetail", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.UpdateDisbursementDetailRequestBody Body;
        
        public UpdateDisbursementDetailRequest() {
        }
        
        public UpdateDisbursementDetailRequest(Elephtan.DisbursementService.UpdateDisbursementDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class UpdateDisbursementDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementDetailManageRequest request;
        
        public UpdateDisbursementDetailRequestBody() {
        }
        
        public UpdateDisbursementDetailRequestBody(Elephtan.DisbursementService.DisbursementDetailManageRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDisbursementDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDisbursementDetailResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.DisbursementService.UpdateDisbursementDetailResponseBody Body;
        
        public UpdateDisbursementDetailResponse() {
        }
        
        public UpdateDisbursementDetailResponse(Elephtan.DisbursementService.UpdateDisbursementDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class UpdateDisbursementDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.DisbursementService.DisbursementDetailManageResponse UpdateDisbursementDetailResult;
        
        public UpdateDisbursementDetailResponseBody() {
        }
        
        public UpdateDisbursementDetailResponseBody(Elephtan.DisbursementService.DisbursementDetailManageResponse UpdateDisbursementDetailResult) {
            this.UpdateDisbursementDetailResult = UpdateDisbursementDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DisbursementServiceSoapChannel : Elephtan.DisbursementService.DisbursementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisbursementServiceSoapClient : System.ServiceModel.ClientBase<Elephtan.DisbursementService.DisbursementServiceSoap>, Elephtan.DisbursementService.DisbursementServiceSoap {
        
        public DisbursementServiceSoapClient() {
        }
        
        public DisbursementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisbursementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisbursementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisbursementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.GenerateDisbursementFormResponse Elephtan.DisbursementService.DisbursementServiceSoap.GenerateDisbursementForm(Elephtan.DisbursementService.GenerateDisbursementFormRequest request) {
            return base.Channel.GenerateDisbursementForm(request);
        }
        
        public Elephtan.DisbursementService.DisbursementManageResponse GenerateDisbursementForm(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.GenerateDisbursementFormRequest inValue = new Elephtan.DisbursementService.GenerateDisbursementFormRequest();
            inValue.Body = new Elephtan.DisbursementService.GenerateDisbursementFormRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.GenerateDisbursementFormResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).GenerateDisbursementForm(inValue);
            return retVal.Body.GenerateDisbursementFormResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.GenerateDisbursementFormResponse> Elephtan.DisbursementService.DisbursementServiceSoap.GenerateDisbursementFormAsync(Elephtan.DisbursementService.GenerateDisbursementFormRequest request) {
            return base.Channel.GenerateDisbursementFormAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.GenerateDisbursementFormResponse> GenerateDisbursementFormAsync(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.GenerateDisbursementFormRequest inValue = new Elephtan.DisbursementService.GenerateDisbursementFormRequest();
            inValue.Body = new Elephtan.DisbursementService.GenerateDisbursementFormRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).GenerateDisbursementFormAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.QueryDisbursementListResponse Elephtan.DisbursementService.DisbursementServiceSoap.QueryDisbursementList(Elephtan.DisbursementService.QueryDisbursementListRequest request) {
            return base.Channel.QueryDisbursementList(request);
        }
        
        public Elephtan.DisbursementService.DisbursementFindListResponse QueryDisbursementList(Elephtan.DisbursementService.DisbursementFindListRequest request) {
            Elephtan.DisbursementService.QueryDisbursementListRequest inValue = new Elephtan.DisbursementService.QueryDisbursementListRequest();
            inValue.Body = new Elephtan.DisbursementService.QueryDisbursementListRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.QueryDisbursementListResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).QueryDisbursementList(inValue);
            return retVal.Body.QueryDisbursementListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementListResponse> Elephtan.DisbursementService.DisbursementServiceSoap.QueryDisbursementListAsync(Elephtan.DisbursementService.QueryDisbursementListRequest request) {
            return base.Channel.QueryDisbursementListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementListResponse> QueryDisbursementListAsync(Elephtan.DisbursementService.DisbursementFindListRequest request) {
            Elephtan.DisbursementService.QueryDisbursementListRequest inValue = new Elephtan.DisbursementService.QueryDisbursementListRequest();
            inValue.Body = new Elephtan.DisbursementService.QueryDisbursementListRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).QueryDisbursementListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.QueryDisbursementByIdResponse Elephtan.DisbursementService.DisbursementServiceSoap.QueryDisbursementById(Elephtan.DisbursementService.QueryDisbursementByIdRequest request) {
            return base.Channel.QueryDisbursementById(request);
        }
        
        public Elephtan.DisbursementService.DisbursementFindResponse QueryDisbursementById(Elephtan.DisbursementService.DisbursementFindRequest request) {
            Elephtan.DisbursementService.QueryDisbursementByIdRequest inValue = new Elephtan.DisbursementService.QueryDisbursementByIdRequest();
            inValue.Body = new Elephtan.DisbursementService.QueryDisbursementByIdRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.QueryDisbursementByIdResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).QueryDisbursementById(inValue);
            return retVal.Body.QueryDisbursementByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementByIdResponse> Elephtan.DisbursementService.DisbursementServiceSoap.QueryDisbursementByIdAsync(Elephtan.DisbursementService.QueryDisbursementByIdRequest request) {
            return base.Channel.QueryDisbursementByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.QueryDisbursementByIdResponse> QueryDisbursementByIdAsync(Elephtan.DisbursementService.DisbursementFindRequest request) {
            Elephtan.DisbursementService.QueryDisbursementByIdRequest inValue = new Elephtan.DisbursementService.QueryDisbursementByIdRequest();
            inValue.Body = new Elephtan.DisbursementService.QueryDisbursementByIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).QueryDisbursementByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse Elephtan.DisbursementService.DisbursementServiceSoap.ConfirmDepartmentDisbursement(Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest request) {
            return base.Channel.ConfirmDepartmentDisbursement(request);
        }
        
        public Elephtan.DisbursementService.DisbursementManageResponse ConfirmDepartmentDisbursement(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest inValue = new Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest();
            inValue.Body = new Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).ConfirmDepartmentDisbursement(inValue);
            return retVal.Body.ConfirmDepartmentDisbursementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse> Elephtan.DisbursementService.DisbursementServiceSoap.ConfirmDepartmentDisbursementAsync(Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest request) {
            return base.Channel.ConfirmDepartmentDisbursementAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmDepartmentDisbursementResponse> ConfirmDepartmentDisbursementAsync(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest inValue = new Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequest();
            inValue.Body = new Elephtan.DisbursementService.ConfirmDepartmentDisbursementRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).ConfirmDepartmentDisbursementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.ConfirmStoreDisbursementResponse Elephtan.DisbursementService.DisbursementServiceSoap.ConfirmStoreDisbursement(Elephtan.DisbursementService.ConfirmStoreDisbursementRequest request) {
            return base.Channel.ConfirmStoreDisbursement(request);
        }
        
        public Elephtan.DisbursementService.DisbursementManageResponse ConfirmStoreDisbursement(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.ConfirmStoreDisbursementRequest inValue = new Elephtan.DisbursementService.ConfirmStoreDisbursementRequest();
            inValue.Body = new Elephtan.DisbursementService.ConfirmStoreDisbursementRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.ConfirmStoreDisbursementResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).ConfirmStoreDisbursement(inValue);
            return retVal.Body.ConfirmStoreDisbursementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmStoreDisbursementResponse> Elephtan.DisbursementService.DisbursementServiceSoap.ConfirmStoreDisbursementAsync(Elephtan.DisbursementService.ConfirmStoreDisbursementRequest request) {
            return base.Channel.ConfirmStoreDisbursementAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.ConfirmStoreDisbursementResponse> ConfirmStoreDisbursementAsync(Elephtan.DisbursementService.DisbursementManageRequest request) {
            Elephtan.DisbursementService.ConfirmStoreDisbursementRequest inValue = new Elephtan.DisbursementService.ConfirmStoreDisbursementRequest();
            inValue.Body = new Elephtan.DisbursementService.ConfirmStoreDisbursementRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).ConfirmStoreDisbursementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.DisbursementService.UpdateDisbursementDetailResponse Elephtan.DisbursementService.DisbursementServiceSoap.UpdateDisbursementDetail(Elephtan.DisbursementService.UpdateDisbursementDetailRequest request) {
            return base.Channel.UpdateDisbursementDetail(request);
        }
        
        public Elephtan.DisbursementService.DisbursementDetailManageResponse UpdateDisbursementDetail(Elephtan.DisbursementService.DisbursementDetailManageRequest request) {
            Elephtan.DisbursementService.UpdateDisbursementDetailRequest inValue = new Elephtan.DisbursementService.UpdateDisbursementDetailRequest();
            inValue.Body = new Elephtan.DisbursementService.UpdateDisbursementDetailRequestBody();
            inValue.Body.request = request;
            Elephtan.DisbursementService.UpdateDisbursementDetailResponse retVal = ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).UpdateDisbursementDetail(inValue);
            return retVal.Body.UpdateDisbursementDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.DisbursementService.UpdateDisbursementDetailResponse> Elephtan.DisbursementService.DisbursementServiceSoap.UpdateDisbursementDetailAsync(Elephtan.DisbursementService.UpdateDisbursementDetailRequest request) {
            return base.Channel.UpdateDisbursementDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.DisbursementService.UpdateDisbursementDetailResponse> UpdateDisbursementDetailAsync(Elephtan.DisbursementService.DisbursementDetailManageRequest request) {
            Elephtan.DisbursementService.UpdateDisbursementDetailRequest inValue = new Elephtan.DisbursementService.UpdateDisbursementDetailRequest();
            inValue.Body = new Elephtan.DisbursementService.UpdateDisbursementDetailRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.DisbursementService.DisbursementServiceSoap)(this)).UpdateDisbursementDetailAsync(inValue);
        }
    }
}
