//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elephtan.AdjustmentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.AdjustmentService.AdjustmentFindRequest))]
    public partial class RequestMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestUserNo {
            get {
                return this.RequestUserNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserNoField, value) != true)) {
                    this.RequestUserNoField = value;
                    this.RaisePropertyChanged("RequestUserNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestUserId {
            get {
                return this.RequestUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestUserIdField, value) != true)) {
                    this.RequestUserIdField = value;
                    this.RaisePropertyChanged("RequestUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustmentFindRequest", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class AdjustmentFindRequest : Elephtan.AdjustmentService.RequestMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustementNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustmentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityAdjustedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AdjustmentId {
            get {
                return this.AdjustmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustmentIdField, value) != true)) {
                    this.AdjustmentIdField = value;
                    this.RaisePropertyChanged("AdjustmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdjustementNo {
            get {
                return this.AdjustementNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustementNoField, value) != true)) {
                    this.AdjustementNoField = value;
                    this.RaisePropertyChanged("AdjustementNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateTimeField, value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTimeField, value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AdjustmentStatus {
            get {
                return this.AdjustmentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustmentStatusField, value) != true)) {
                    this.AdjustmentStatusField = value;
                    this.RaisePropertyChanged("AdjustmentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DetailId {
            get {
                return this.DetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailIdField, value) != true)) {
                    this.DetailIdField = value;
                    this.RaisePropertyChanged("DetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string QuantityAdjusted {
            get {
                return this.QuantityAdjustedField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityAdjustedField, value) != true)) {
                    this.QuantityAdjustedField = value;
                    this.RaisePropertyChanged("QuantityAdjusted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.AdjustmentService.AdjustmentFindResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Elephtan.AdjustmentService.AdjustmentFindListResponse))]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceResponseMessgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseCode {
            get {
                return this.ServiceResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseCodeField, value) != true)) {
                    this.ServiceResponseCodeField = value;
                    this.RaisePropertyChanged("ServiceResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceResponseMessge {
            get {
                return this.ServiceResponseMessgeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseMessgeField, value) != true)) {
                    this.ServiceResponseMessgeField = value;
                    this.RaisePropertyChanged("ServiceResponseMessge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustmentFindResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class AdjustmentFindResponse : Elephtan.AdjustmentService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustementNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdjustmentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityAdjustedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.AdjustmentService.AdjustmentDetail[] AdjustmentDetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Totalamount1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AdjustmentId {
            get {
                return this.AdjustmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustmentIdField, value) != true)) {
                    this.AdjustmentIdField = value;
                    this.RaisePropertyChanged("AdjustmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdjustementNo {
            get {
                return this.AdjustementNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustementNoField, value) != true)) {
                    this.AdjustementNoField = value;
                    this.RaisePropertyChanged("AdjustementNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateTimeField, value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTimeField, value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AdjustmentStatus {
            get {
                return this.AdjustmentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustmentStatusField, value) != true)) {
                    this.AdjustmentStatusField = value;
                    this.RaisePropertyChanged("AdjustmentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DetailId {
            get {
                return this.DetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailIdField, value) != true)) {
                    this.DetailIdField = value;
                    this.RaisePropertyChanged("DetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string QuantityAdjusted {
            get {
                return this.QuantityAdjustedField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityAdjustedField, value) != true)) {
                    this.QuantityAdjustedField = value;
                    this.RaisePropertyChanged("QuantityAdjusted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public Elephtan.AdjustmentService.AdjustmentDetail[] AdjustmentDetailList {
            get {
                return this.AdjustmentDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjustmentDetailListField, value) != true)) {
                    this.AdjustmentDetailListField = value;
                    this.RaisePropertyChanged("AdjustmentDetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Totalamount1 {
            get {
                return this.Totalamount1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Totalamount1Field, value) != true)) {
                    this.Totalamount1Field = value;
                    this.RaisePropertyChanged("Totalamount1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustmentFindListResponse", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class AdjustmentFindListResponse : Elephtan.AdjustmentService.ResponseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.AdjustmentService.AdjustmentFindResponse[] ListResponserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Elephtan.AdjustmentService.AdjustmentDetail[] ListAdjustmentDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Elephtan.AdjustmentService.AdjustmentFindResponse[] ListResponser {
            get {
                return this.ListResponserField;
            }
            set {
                if ((object.ReferenceEquals(this.ListResponserField, value) != true)) {
                    this.ListResponserField = value;
                    this.RaisePropertyChanged("ListResponser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Elephtan.AdjustmentService.AdjustmentDetail[] ListAdjustmentDetails {
            get {
                return this.ListAdjustmentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListAdjustmentDetailsField, value) != true)) {
                    this.ListAdjustmentDetailsField = value;
                    this.RaisePropertyChanged("ListAdjustmentDetails");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustmentDetail", Namespace="http://www.nus.edu.sg/storeservcie")]
    [System.SerializableAttribute()]
    public partial class AdjustmentDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityAdjustedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DetailId {
            get {
                return this.DetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailIdField, value) != true)) {
                    this.DetailIdField = value;
                    this.RaisePropertyChanged("DetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string QuantityAdjusted {
            get {
                return this.QuantityAdjustedField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityAdjustedField, value) != true)) {
                    this.QuantityAdjustedField = value;
                    this.RaisePropertyChanged("QuantityAdjusted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie", ConfigurationName="AdjustmentService.AdjustmentServiceSoap")]
    public interface AdjustmentServiceSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryAdjustList", ReplyAction="*")]
        Elephtan.AdjustmentService.QueryAdjustListResponse QueryAdjustList(Elephtan.AdjustmentService.QueryAdjustListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryAdjustList", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustListResponse> QueryAdjustListAsync(Elephtan.AdjustmentService.QueryAdjustListRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryAdjustById", ReplyAction="*")]
        Elephtan.AdjustmentService.QueryAdjustByIdResponse QueryAdjustById(Elephtan.AdjustmentService.QueryAdjustByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/QueryAdjustById", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustByIdResponse> QueryAdjustByIdAsync(Elephtan.AdjustmentService.QueryAdjustByIdRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/createAdjustment", ReplyAction="*")]
        Elephtan.AdjustmentService.createAdjustmentResponse createAdjustment(Elephtan.AdjustmentService.createAdjustmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/createAdjustment", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.createAdjustmentResponse> createAdjustmentAsync(Elephtan.AdjustmentService.createAdjustmentRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/updateadjustment", ReplyAction="*")]
        Elephtan.AdjustmentService.updateadjustmentResponse updateadjustment(Elephtan.AdjustmentService.updateadjustmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/updateadjustment", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.updateadjustmentResponse> updateadjustmentAsync(Elephtan.AdjustmentService.updateadjustmentRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://www.nus.edu.sg/storeservcie is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/viewdetails", ReplyAction="*")]
        Elephtan.AdjustmentService.viewdetailsResponse viewdetails(Elephtan.AdjustmentService.viewdetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nus.edu.sg/storeservcie/viewdetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.viewdetailsResponse> viewdetailsAsync(Elephtan.AdjustmentService.viewdetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAdjustListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAdjustList", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.QueryAdjustListRequestBody Body;
        
        public QueryAdjustListRequest() {
        }
        
        public QueryAdjustListRequest(Elephtan.AdjustmentService.QueryAdjustListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryAdjustListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindRequest request;
        
        public QueryAdjustListRequestBody() {
        }
        
        public QueryAdjustListRequestBody(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAdjustListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAdjustListResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.QueryAdjustListResponseBody Body;
        
        public QueryAdjustListResponse() {
        }
        
        public QueryAdjustListResponse(Elephtan.AdjustmentService.QueryAdjustListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryAdjustListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindListResponse QueryAdjustListResult;
        
        public QueryAdjustListResponseBody() {
        }
        
        public QueryAdjustListResponseBody(Elephtan.AdjustmentService.AdjustmentFindListResponse QueryAdjustListResult) {
            this.QueryAdjustListResult = QueryAdjustListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAdjustByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAdjustById", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.QueryAdjustByIdRequestBody Body;
        
        public QueryAdjustByIdRequest() {
        }
        
        public QueryAdjustByIdRequest(Elephtan.AdjustmentService.QueryAdjustByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryAdjustByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindRequest request;
        
        public QueryAdjustByIdRequestBody() {
        }
        
        public QueryAdjustByIdRequestBody(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryAdjustByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryAdjustByIdResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.QueryAdjustByIdResponseBody Body;
        
        public QueryAdjustByIdResponse() {
        }
        
        public QueryAdjustByIdResponse(Elephtan.AdjustmentService.QueryAdjustByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class QueryAdjustByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindResponse QueryAdjustByIdResult;
        
        public QueryAdjustByIdResponseBody() {
        }
        
        public QueryAdjustByIdResponseBody(Elephtan.AdjustmentService.AdjustmentFindResponse QueryAdjustByIdResult) {
            this.QueryAdjustByIdResult = QueryAdjustByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdjustmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAdjustment", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.createAdjustmentRequestBody Body;
        
        public createAdjustmentRequest() {
        }
        
        public createAdjustmentRequest(Elephtan.AdjustmentService.createAdjustmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class createAdjustmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindRequest request;
        
        public createAdjustmentRequestBody() {
        }
        
        public createAdjustmentRequestBody(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createAdjustmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createAdjustmentResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.createAdjustmentResponseBody Body;
        
        public createAdjustmentResponse() {
        }
        
        public createAdjustmentResponse(Elephtan.AdjustmentService.createAdjustmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class createAdjustmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindResponse createAdjustmentResult;
        
        public createAdjustmentResponseBody() {
        }
        
        public createAdjustmentResponseBody(Elephtan.AdjustmentService.AdjustmentFindResponse createAdjustmentResult) {
            this.createAdjustmentResult = createAdjustmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateadjustmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateadjustment", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.updateadjustmentRequestBody Body;
        
        public updateadjustmentRequest() {
        }
        
        public updateadjustmentRequest(Elephtan.AdjustmentService.updateadjustmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class updateadjustmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindRequest request;
        
        public updateadjustmentRequestBody() {
        }
        
        public updateadjustmentRequestBody(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateadjustmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateadjustmentResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.updateadjustmentResponseBody Body;
        
        public updateadjustmentResponse() {
        }
        
        public updateadjustmentResponse(Elephtan.AdjustmentService.updateadjustmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class updateadjustmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindResponse updateadjustmentResult;
        
        public updateadjustmentResponseBody() {
        }
        
        public updateadjustmentResponseBody(Elephtan.AdjustmentService.AdjustmentFindResponse updateadjustmentResult) {
            this.updateadjustmentResult = updateadjustmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class viewdetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="viewdetails", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.viewdetailsRequestBody Body;
        
        public viewdetailsRequest() {
        }
        
        public viewdetailsRequest(Elephtan.AdjustmentService.viewdetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class viewdetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindRequest request;
        
        public viewdetailsRequestBody() {
        }
        
        public viewdetailsRequestBody(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class viewdetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="viewdetailsResponse", Namespace="http://www.nus.edu.sg/storeservcie", Order=0)]
        public Elephtan.AdjustmentService.viewdetailsResponseBody Body;
        
        public viewdetailsResponse() {
        }
        
        public viewdetailsResponse(Elephtan.AdjustmentService.viewdetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nus.edu.sg/storeservcie")]
    public partial class viewdetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Elephtan.AdjustmentService.AdjustmentFindListResponse viewdetailsResult;
        
        public viewdetailsResponseBody() {
        }
        
        public viewdetailsResponseBody(Elephtan.AdjustmentService.AdjustmentFindListResponse viewdetailsResult) {
            this.viewdetailsResult = viewdetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdjustmentServiceSoapChannel : Elephtan.AdjustmentService.AdjustmentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdjustmentServiceSoapClient : System.ServiceModel.ClientBase<Elephtan.AdjustmentService.AdjustmentServiceSoap>, Elephtan.AdjustmentService.AdjustmentServiceSoap {
        
        public AdjustmentServiceSoapClient() {
        }
        
        public AdjustmentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdjustmentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdjustmentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdjustmentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.AdjustmentService.QueryAdjustListResponse Elephtan.AdjustmentService.AdjustmentServiceSoap.QueryAdjustList(Elephtan.AdjustmentService.QueryAdjustListRequest request) {
            return base.Channel.QueryAdjustList(request);
        }
        
        public Elephtan.AdjustmentService.AdjustmentFindListResponse QueryAdjustList(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.QueryAdjustListRequest inValue = new Elephtan.AdjustmentService.QueryAdjustListRequest();
            inValue.Body = new Elephtan.AdjustmentService.QueryAdjustListRequestBody();
            inValue.Body.request = request;
            Elephtan.AdjustmentService.QueryAdjustListResponse retVal = ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).QueryAdjustList(inValue);
            return retVal.Body.QueryAdjustListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustListResponse> Elephtan.AdjustmentService.AdjustmentServiceSoap.QueryAdjustListAsync(Elephtan.AdjustmentService.QueryAdjustListRequest request) {
            return base.Channel.QueryAdjustListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustListResponse> QueryAdjustListAsync(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.QueryAdjustListRequest inValue = new Elephtan.AdjustmentService.QueryAdjustListRequest();
            inValue.Body = new Elephtan.AdjustmentService.QueryAdjustListRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).QueryAdjustListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.AdjustmentService.QueryAdjustByIdResponse Elephtan.AdjustmentService.AdjustmentServiceSoap.QueryAdjustById(Elephtan.AdjustmentService.QueryAdjustByIdRequest request) {
            return base.Channel.QueryAdjustById(request);
        }
        
        public Elephtan.AdjustmentService.AdjustmentFindResponse QueryAdjustById(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.QueryAdjustByIdRequest inValue = new Elephtan.AdjustmentService.QueryAdjustByIdRequest();
            inValue.Body = new Elephtan.AdjustmentService.QueryAdjustByIdRequestBody();
            inValue.Body.request = request;
            Elephtan.AdjustmentService.QueryAdjustByIdResponse retVal = ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).QueryAdjustById(inValue);
            return retVal.Body.QueryAdjustByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustByIdResponse> Elephtan.AdjustmentService.AdjustmentServiceSoap.QueryAdjustByIdAsync(Elephtan.AdjustmentService.QueryAdjustByIdRequest request) {
            return base.Channel.QueryAdjustByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.AdjustmentService.QueryAdjustByIdResponse> QueryAdjustByIdAsync(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.QueryAdjustByIdRequest inValue = new Elephtan.AdjustmentService.QueryAdjustByIdRequest();
            inValue.Body = new Elephtan.AdjustmentService.QueryAdjustByIdRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).QueryAdjustByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.AdjustmentService.createAdjustmentResponse Elephtan.AdjustmentService.AdjustmentServiceSoap.createAdjustment(Elephtan.AdjustmentService.createAdjustmentRequest request) {
            return base.Channel.createAdjustment(request);
        }
        
        public Elephtan.AdjustmentService.AdjustmentFindResponse createAdjustment(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.createAdjustmentRequest inValue = new Elephtan.AdjustmentService.createAdjustmentRequest();
            inValue.Body = new Elephtan.AdjustmentService.createAdjustmentRequestBody();
            inValue.Body.request = request;
            Elephtan.AdjustmentService.createAdjustmentResponse retVal = ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).createAdjustment(inValue);
            return retVal.Body.createAdjustmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.createAdjustmentResponse> Elephtan.AdjustmentService.AdjustmentServiceSoap.createAdjustmentAsync(Elephtan.AdjustmentService.createAdjustmentRequest request) {
            return base.Channel.createAdjustmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.AdjustmentService.createAdjustmentResponse> createAdjustmentAsync(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.createAdjustmentRequest inValue = new Elephtan.AdjustmentService.createAdjustmentRequest();
            inValue.Body = new Elephtan.AdjustmentService.createAdjustmentRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).createAdjustmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.AdjustmentService.updateadjustmentResponse Elephtan.AdjustmentService.AdjustmentServiceSoap.updateadjustment(Elephtan.AdjustmentService.updateadjustmentRequest request) {
            return base.Channel.updateadjustment(request);
        }
        
        public Elephtan.AdjustmentService.AdjustmentFindResponse updateadjustment(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.updateadjustmentRequest inValue = new Elephtan.AdjustmentService.updateadjustmentRequest();
            inValue.Body = new Elephtan.AdjustmentService.updateadjustmentRequestBody();
            inValue.Body.request = request;
            Elephtan.AdjustmentService.updateadjustmentResponse retVal = ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).updateadjustment(inValue);
            return retVal.Body.updateadjustmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.updateadjustmentResponse> Elephtan.AdjustmentService.AdjustmentServiceSoap.updateadjustmentAsync(Elephtan.AdjustmentService.updateadjustmentRequest request) {
            return base.Channel.updateadjustmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.AdjustmentService.updateadjustmentResponse> updateadjustmentAsync(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.updateadjustmentRequest inValue = new Elephtan.AdjustmentService.updateadjustmentRequest();
            inValue.Body = new Elephtan.AdjustmentService.updateadjustmentRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).updateadjustmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Elephtan.AdjustmentService.viewdetailsResponse Elephtan.AdjustmentService.AdjustmentServiceSoap.viewdetails(Elephtan.AdjustmentService.viewdetailsRequest request) {
            return base.Channel.viewdetails(request);
        }
        
        public Elephtan.AdjustmentService.AdjustmentFindListResponse viewdetails(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.viewdetailsRequest inValue = new Elephtan.AdjustmentService.viewdetailsRequest();
            inValue.Body = new Elephtan.AdjustmentService.viewdetailsRequestBody();
            inValue.Body.request = request;
            Elephtan.AdjustmentService.viewdetailsResponse retVal = ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).viewdetails(inValue);
            return retVal.Body.viewdetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Elephtan.AdjustmentService.viewdetailsResponse> Elephtan.AdjustmentService.AdjustmentServiceSoap.viewdetailsAsync(Elephtan.AdjustmentService.viewdetailsRequest request) {
            return base.Channel.viewdetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Elephtan.AdjustmentService.viewdetailsResponse> viewdetailsAsync(Elephtan.AdjustmentService.AdjustmentFindRequest request) {
            Elephtan.AdjustmentService.viewdetailsRequest inValue = new Elephtan.AdjustmentService.viewdetailsRequest();
            inValue.Body = new Elephtan.AdjustmentService.viewdetailsRequestBody();
            inValue.Body.request = request;
            return ((Elephtan.AdjustmentService.AdjustmentServiceSoap)(this)).viewdetailsAsync(inValue);
        }
    }
}
